[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_BACKEND_URL = "https://your-backend-url.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 